using Microsoft.CodeAnalysis;
using System;

namespace SourceGenerators.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class GreetingsGenerator : IIncrementalGenerator
{
    private const string Namespace = "This.Was.SourceGenerated";
    private const string TypeName = "Greetings";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit static source once at post-init time
        context.RegisterPostInitializationOutput(static spc =>
        {
            var generationTime = DateTime.UtcNow;
            var source =
                $$"""
                  // <auto-generated/>
                  // This code was auto generated 
                  //    by {{typeof(GreetingsGenerator).Namespace}}.{{nameof(GreetingsGenerator)}}
                  //    at {{generationTime:O}}

                  using System;

                  namespace {{Namespace}}
                  {
                      public static class {{TypeName}}
                      {
                          //A property that
                          public const long GeneratedAtUtcTicks = {{generationTime.Ticks}};
                          public static readonly DateTime GeneratedAtUtc = new(GeneratedAtUtcTicks);
                      
                      
                          //A method that greets the caller with the given name
                          public static void HelloFrom(string name = "world") =>
                              Console.WriteLine($"Generator says: Hi from '{name}'");
                      }
                  }
                  """;

            spc.AddSource($"{TypeName}.g.cs", source);
        });
    }
}